# Generated by Django 4.2.18 on 2025-03-14 01:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 14, 1, 45, 8, 258640, tzinfo=datetime.timezone.utc)),
        ),
    ]
