# Generated by Django 4.2.18 on 2025-03-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('patron', 'Patron'), ('librarian', 'Librarian')], default='patron', max_length=20),
        ),
    ]
