# Generated by Django 4.2.18 on 2025-03-10 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes_app', '0002_note_is_requested_patronrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='profile-pictures/')),
                ('preferred_named', models.TextField(blank=True)),
                ('preferred_pronouns', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
