# Generated by Django 4.2.18 on 2025-03-10 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes_app", "0002_note_is_requested_patronrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="date",
        ),
    ]
