# Generated by Django 4.2.20 on 2025-04-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes_app", "0002_alter_notereview_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestnote",
            name="is_viewed",
            field=models.BooleanField(default=False),
        ),
    ]
