# Generated by Django 4.2.18 on 2025-03-18 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0002_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
