# Generated by Django 4.2.20 on 2025-03-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes_app", "0002_privatecollectionpatron"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
