# Generated by Django 4.2.18 on 2025-03-11 20:40

from django.db import migrations, models
import storages.backends.s3


class Migration(migrations.Migration):
    dependencies = [
        ("notes_app", "0003_remove_note_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="collections",
        ),
        migrations.RemoveField(
            model_name="note",
            name="privacy",
        ),
        migrations.RemoveField(
            model_name="note",
            name="visibility",
        ),
        migrations.AlterField(
            model_name="note",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="file",
            field=models.FileField(
                storage=storages.backends.s3.S3Storage(), upload_to="notes/"
            ),
        ),
    ]
