# Generated by Django 4.2.20 on 2025-04-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes_app", "0003_requestnote_is_viewed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="requestnote",
            old_name="is_viewed",
            new_name="librarian_viewed_notification",
        ),
        migrations.AddField(
            model_name="requestnote",
            name="requester_viewed_notification",
            field=models.BooleanField(default=False),
        ),
    ]
