# Generated by Django 4.2.20 on 2025-04-29 12:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "notes_app",
            "0004_rename_is_viewed_requestnote_librarian_viewed_notification_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="preferred_named",
            new_name="preferred_name",
        ),
    ]
