# Generated by Django 4.2.18 on 2025-03-30 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0004_notereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notereview',
            name='rating',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
