# Generated by Django 4.2.18 on 2025-03-11 21:11

from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3


class Migration(migrations.Migration):
    dependencies = [
        ("notes_app", "0004_remove_note_collections_remove_note_privacy_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="file",
        ),
        migrations.CreateModel(
            name="NoteFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=storages.backends.s3.S3Storage(), upload_to="notes/"
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="notes_app.note"
                    ),
                ),
            ],
        ),
    ]
