# Generated by Django 4.2.18 on 2025-03-10 22:50

from django.db import migrations, models
import storages.backends.s3


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0004_alter_note_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(null=True, storage=storages.backends.s3.S3Storage(), upload_to='profile-pictures/'),
        ),
    ]
