# Generated by Django 4.2.18 on 2025-03-11 05:29

from django.db import migrations, models
import storages.backends.s3


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0006_alter_profile_preferred_named_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/static/notes_app/images/default_profile.png', storage=storages.backends.s3.S3Storage(), upload_to='profile-pictures/'),
        ),
    ]
