# Generated by Django 4.2.18 on 2025-04-03 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0006_patronrequest_fulfilled_at_collectionaccessrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notereview',
            name='rating',
            field=models.FloatField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
