# Generated by Django 4.2.18 on 2025-03-11 05:33

from django.db import migrations, models
import storages.backends.s3


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0008_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, storage=storages.backends.s3.S3Storage(), upload_to='profile-pictures/'),
        ),
    ]
