# Generated by Django 4.2.18 on 2025-03-12 18:10

from django.db import migrations, models
import storages.backends.s3


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0009_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=models.ImageField(blank=True, default=None, null=True, storage=storages.backends.s3.S3Storage(), upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, storage=storages.backends.s3.S3Storage(), upload_to='profile-pictures/'),
        ),
    ]
